server:
  port: 9092
spring:
    application:
        name: batchService
    cloud:
      services:
        registrationMethod: route
    #DATABASE CONFIG ISSUE: CANNOT USE ENVIRONMENT VARIABLE
    datasource:
        url: jdbc:oracle:thin:@assignforce.chueiwozbnfz.us-east-1.rds.amazonaws.com:1521:ORCL
        username: assignforce_dev
        password: pVCwxTn3
#        url: ${DB_URL}
#        username: ${DB_USER}
#        password: ${DB_PASSWORD}
    #HIBERNATE
    jpa:
        database-platform: org.hibernate.dialect.Oracle10gDialect
producer:          
 ribbon:
   ServerListRefreshInterval: 5000
ribbon:
 isSecure: false  
security:
 basic:
   enabled: false