spring:
  application:
    name: assignforce-edge-server
management:
  security:
    enabled: false

#Zuul with Eureka
zuul:
  prefix: /api
  routes:
    batches:
      path: /batches/**
      serviceId: assignforce-batches-service

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      lease-expiration-duration-in-seconds: 2
      lease-renewal-interval-in-seconds: 1

security:
  oauth2:
    client:
      clientId: 3MVG9ahGHqp.k2_wb8eUMtoR38zX8fWod2YBcK5.4RRrWling4BGamz7JanMJTUGcXxI9qda4fQh3xU0Q9EBH
      clientSecret: ${OAUTH_CLIENT_SECRET}
      accessTokenUri: https://revature--int1.cs17.my.salesforce.com/services/oauth2/token
      userAuthorizationUri: https://revature--int1.cs17.my.salesforce.com/services/oauth2/authorize?prompt=login
      tokenName: authorization_code
      authenticationScheme: header
      clientAuthenticationScheme: form
      grantType: authorization_code
      preEstablishedRedirectUri: https://localhost:8443/home
      #registeredRedirectUri: https://localhost:8443/
      #useCurrentUri: false
    resource:
      userInfoUri: https://revature--int1.cs17.my.salesforce.com/services/oauth2/userinfo
#  ignored: /api/v2/google/**
server:
  port: 443
  ssl:
    keyStore: classpath:keystore.jks
    keyStorePassword: password
    keyStoreType: jks
    keyAlias: selfsigned
 
frontEndUrl: http://localhost:4200
