--------------------------------------------------------
--  File created - Friday-December-15-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CURRICULUM_SKILL_JT
--------------------------------------------------------

  CREATE TABLE CURRICULUM_SKILL_JT 
   (	"CURRICULUM_ID" NUMBER(10,0), 
	"SKILL_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CURRICULUM_SKILL_JT
SET DEFINE OFF;
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (284,115);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (284,58);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (284,73);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (24,47);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (24,50);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (24,51);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (24,4);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (24,1);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (267,60);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (124,50);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (124,4);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (124,1);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (105,51);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (105,4);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (105,59);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (105,66);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (1,1);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (1,53);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (1,106);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (124,2);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (124,3);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (124,48);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (124,49);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (124,53);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (124,55);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (1,55);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (1,49);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (1,108);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (1,110);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (1,50);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (1,48);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (1,54);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (1,2);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (1,25);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (1,56);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (84,91);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (1,86);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (1,57);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (1,3);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (1,69);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (252,4);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (124,56);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (124,57);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (2,4);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (2,4);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (2,59);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (2,59);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (2,60);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (2,60);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (2,58);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (2,66);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (2,66);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (2,62);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (2,67);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (2,65);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (2,63);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (2,64);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (2,61);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (2,46);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (2,111);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (252,115);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (253,108);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (267,111);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (267,66);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (3,47);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (3,5);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (4,3);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (3,69);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (3,72);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (3,70);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (3,71);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (3,68);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (149,46);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (149,65);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (149,86);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (4,4);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (4,55);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (4,56);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (150,66);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (150,111);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (150,4);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (104,90);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (104,106);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (104,108);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (144,1);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (144,25);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (164,4);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (164,59);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (164,60);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (250,4);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (251,4);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (248,4);
Insert into CURRICULUM_SKILL_JT (CURRICULUM_ID,SKILL_ID) values (248,59);
--------------------------------------------------------
--  Constraints for Table CURRICULUM_SKILL_JT
--------------------------------------------------------

  ALTER TABLE CURRICULUM_SKILL_JT MODIFY ("SKILL_ID" NOT NULL ENABLE);
  ALTER TABLE CURRICULUM_SKILL_JT MODIFY ("CURRICULUM_ID" NOT NULL ENABLE);
  
  commit;


--------------
-- ALTER to add foreign key
--------------
ALTER TABLE CURRICULUM_SKILL_JT ADD CONSTRAINT FK_CURRICULUMID
FOREIGN KEY (CURRICULUM_ID) REFERENCES CURRICULUM(ID);
COMMIT;




-----------------------
-- ELEPHANT SQL 
------------------------
  CREATE TABLE CURRICULUM_SKILL_JT 
   (	"CURRICULUM_ID" INTEGER, 
	"SKILL_ID" INTEGER
   )
   
ALTER TABLE CURRICULUM_SKILL_JT ADD CONSTRAINT FK_CURRICULUMID
FOREIGN KEY ("CURRICULUM_ID") REFERENCES CURRICULUM("ID");


  ALTER TABLE CURRICULUM_SKILL_JT ALTER COLUMN "SKILL_ID" SET NOT NULL;
  ALTER TABLE CURRICULUM_SKILL_JT ALTER COLUMN "CURRICULUM_ID" SET NOT NULL;
  


Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (284,115);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (284,58);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (284,73);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (24,47);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (24,50);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (24,51);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (24,4);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (24,1);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (267,60);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (124,50);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (124,4);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (124,1);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (105,51);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (105,4);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (105,59);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (105,66);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (1,1);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (1,53);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (1,106);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (124,2);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (124,3);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (124,48);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (124,49);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (124,53);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (124,55);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (1,55);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (1,49);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (1,108);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (1,110);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (1,50);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (1,48);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (1,54);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (1,2);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (1,25);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (1,56);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (84,91);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (1,86);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (1,57);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (1,3);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (1,69);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (252,4);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (124,56);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (124,57);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (2,4);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (2,4);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (2,59);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (2,59);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (2,60);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (2,60);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (2,58);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (2,66);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (2,66);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (2,62);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (2,67);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (2,65);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (2,63);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (2,64);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (2,61);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (2,46);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (2,111);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (252,115);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (253,108);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (267,111);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (267,66);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (3,47);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (3,5);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (4,3);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (3,69);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (3,72);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (3,70);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (3,71);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (3,68);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (149,46);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (149,65);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (149,86);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (4,4);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (4,55);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (4,56);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (150,66);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (150,111);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (150,4);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (104,90);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (104,106);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (104,108);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (144,1);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (144,25);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (164,4);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (164,59);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (164,60);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (250,4);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (251,4);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (248,4);
Insert into CURRICULUM_SKILL_JT ("CURRICULUM_ID","SKILL_ID") values (248,59);

