--------------------------------------------------------
--  File created - Friday-December-15-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CURRICULUM
--------------------------------------------------------

  CREATE TABLE CURRICULUM 
   (	"ID" NUMBER(10,0), 
	"ACTIVE" NUMBER(1,0), 
	"CORE" NUMBER(1,0), 
	"NAME" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ASSIGNFORCE_DEV.CURRICULUM
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C007846
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007846" ON CURRICULUM ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UK_23YYYB6FC6IB2CRJ9NEIHOGNA
--------------------------------------------------------

  CREATE UNIQUE INDEX "UK_23YYYB6FC6IB2CRJ9NEIHOGNA" ON CURRICULUM ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CURRICULUM
--------------------------------------------------------

  ALTER TABLE CURRICULUM ADD CONSTRAINT "UK_23YYYB6FC6IB2CRJ9NEIHOGNA" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE CURRICULUM ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE CURRICULUM MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE CURRICULUM MODIFY ("ID" NOT NULL ENABLE);
  commit;
  
  
